const projectsData = [

    {name:'Aerolab Challenge',
    id:0,
    tags:['challenge'],
    img:'./imgs/projects/aerolab.png',
    desc:'¡Canjea productos por puntos acumulados! Next JS, Styled Components.',
    website:'https://aerolab-challenge-sntmsc.vercel.app/',
    github:'https://github.com/sntmsc/frontend-developer-coding-challenge',
    footer:'Me encantan los productos tecnológicos'},
    {name:'Cretona Web',
    id:1,
    tags:['e-commerce'],
    img:'./imgs/projects/cretona-socks.jpg',
    desc:'E-commerce diseñado para un emprendimiento. Diseño en CSS. Migración de HTML a React. Pseudo-backend con react-papaparse y Google sheets.',
    website:'https://cretona-socks.netlify.app/',
    github:'https://github.com/sntmsc/Cretona-web-2.0',
    footer:'Las medias son un lindo detalle'},
    {name:'Soundmaster',
    id:2,
    tags:['e-commerce'],
    img:'./imgs/projects/soundmaster.png',
    desc:'E-commerce de instrumentos para crear música electrónica. Tecnologías utilizadas: React, Redux toolkit, Supabase, Chakra UI.',
    website:'https://soundmaster-commerce.netlify.app/',
    github:'https://github.com/sntmsc/e-synths',
    footer:'No hay nada como la síntesis sonora'},
    {name:"Tino's tools",
    id:3,
    tags:['personal','tools'],
    img:'./imgs/projects/tinoTools.png',
    desc:'App de herramientas musicales creadas con Tone.js, React JS y Chakra UI',
    website:'https://tinotools.netlify.app/',
    github:'https://github.com/sntmsc/music-tools',
    footer:"Please don't stop the music"},
    {name:'SuperHero',
    id:4,
    tags:['juego','info'],
    img:'./imgs/projects/superhero.png',
    desc:'Crea tu equipo de superheroes! React, Bootstrap, SuperHero API. Ingrese los siguientes datos: mail:challenge@alkemy.org, password:react',
    website:'https://superhero-sntmsc.netlify.app/',
    github:'https://github.com/sntmsc/alkemy-challenge',
    footer:'¿Cual es tu superhéroe favorito?'},
    {name:'Paises',
    id:5,
    tags:['info'],
    img:'./imgs/projects/paises.png',
    desc:'Página informativa sobre los países. La información se solicita a restcountries.com y openweathermap.org. React JS, Bootstrap, manejo de API REST.',
    website:'https://buscador-de-paises.netlify.app/',
    github:'https://github.com/sntmsc/buscador-de-paises',
    footer:'¡Cuanto mundo por conocer!'},

];

export default projectsData