const projectsData = [
    {name:'Memotest',
    id:0,
    tags:['juego'],
    img:'./imgs/projects/memotest.png',
    desc:'Memotest con 3 niveles de dificultad, timer y contador de intentos. HTML, CSS Y JS.',
    website:'https://sntmsc.github.io/memotest/',
    github:'https://github.com/sntmsc/memotest',
    footer:'Jugar memotest hace bien a la memoria'},
    {name:'To-do List',
    id:1,
    tags:['oficina'],
    img:'./imgs/projects/to-do-list.png',
    desc:'Una lista de tareas creada con React, backend en Firebase, Chakra UI y Framer Motion.',
    website:'https://lista-de-tareas-sntmsc.netlify.app/',
    github:'https://github.com/sntmsc/to-do-list',
    footer:'Aumentá tu productividad'},
    {name:'SuperHero',
    id:2,
    tags:['juego','info'],
    img:'./imgs/projects/superhero.png',
    desc:'Crea tu equipo de superheroes! React, Bootstrap, SuperHero API. Ingrese los siguientes datos: mail:challenge@alkemy.org, password:react',
    website:'https://superhero-sntmsc.netlify.app/',
    github:'https://github.com/sntmsc/alkemy-challenge',
    footer:'¿Cual es tu superhéroe favorito?'},
    {name:'Cretona Web',
    id:3,
    tags:['e-commerce'],
    img:'./imgs/projects/cretona.png',
    desc:'E-commerce diseñado para un emprendimiento. Dseño en CSS. Migración de HTML a React. Pseudo-backend con react-papaparse y Google sheets.',
    website:'https://cretona-socks.netlify.app/',
    github:'https://github.com/sntmsc/Cretona-web-2.0',
    footer:'Mi e-commerce te deja patas para arriba'},
    {name:'Paises',
    id:4,
    tags:['info'],
    img:'./imgs/projects/paises.png',
    desc:'Página informativa sobre los países. La información se solicita a restcountries.com y openweathermap.org. React JS, Bootstrap, manejo de API REST. La idea del proyecto surge de una actividad en Fullstackopen.',
    website:'https://buscador-de-paises.netlify.app/',
    github:'https://github.com/sntmsc/buscador-de-paises',
    footer:'Mantenete informadx!'}
];

export default projectsData